### ISSUE TITLE
Web Search settings

### ISSUE THREAD

**Issue by cerupcat** [filestack/FSPicker#10]
Is there a place to add settings for web search? Right now the results aren't necessary "safe for work". The results for the iOS version don't seem to match web search on the web filepicker. Thanks for any insights!

**Comment by pJes2** [comment]
1. There is no such functionality (to filter NSFW images), neither for iOS nor Web.
2. What is the query you are searching for that displays different results for iOS/Web?

**Comment by cerupcat** [comment]
I realized after that search seems to be the same for both web and mobile, so this isn't mobile specific. We can follow up with support if this isn't your area, but it seems that the results from web search aren't as good as if we searched google search directly. For example, searching for "Snapchat" on filepicker doesn't give logos or snapchat or show any results relating to the app. If you search google search, you get a lot of Snapchat app related images.

**Comment by pJes2** [comment]
From what I've heard after talking to backend guys, we are using google search until we have "API calls" left, since google have some API limits. After reaching the limit, we are using flickr and wikipedia to search for images.
You can try and use your own google app and set it in developer portal -> credentials -> auth keys -> google search. This way, if I'm not wrong, you should get results consistent with google image search while being dependent on your own api call limit.

Either way it is not something I can fix for you from within FSPicker.

**Comment by cerupcat** [comment]
Thanks @pJes2. That's helpful information and we'll look into adding our key so we can control this a bit more. Thanks again!
